export const items = [
  {
    _id: '1',
    image: '/images/airpods.jpg',
    name: 'Airpods Wireless Bluetooth Headphones',
    description: 'Bluetooth technology lets you connect it with a compatible device',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    image: '/images/phone.jpg',
    name: 'iPhone 11 Pro 256GB Memory',
    description: 'Introducing the iPhone 11 Pro',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    image: '/images/camera.jpg',
    name: 'Cannon EOS 80D DSLR Camera',
    description: 'Characterized by versatile imaging',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3.0,
    numReviews: 12,
  },
  {
    _id: '4',
    image: '/images/playstation.jpg',
    name: 'Sony Playstation 4 Pro White Version',
    description: 'Ultimate home entertainment system',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5.0,
    numReviews: 12,
  },
];
